trigger:
  branches:
    include:
      - main

variables:
  githubRepo: 'https://github.com/ajrtvo/StrongPasswordGenerator'
  # githubPAT should be stored as a secret pipeline variable
  githubPAT: '$(githubPAT)' 
  adoRepoDir: '$(Build.SourcesDirectory)'

stages:
  - stage: Sync
    jobs:
      - job: PushToGitHub
        steps:
          - script: |
              git clone --branch main $(Build.Repository.Uri) temp_ado_repo
              cd temp_ado_repo
              # Add GitHub remote with PAT for authentication
              git remote add github https://$(githubPAT)@github.com/ajrtvo/StrongPasswordGenerator.git
              git push github main --force
            displayName: 'Sync Azure DevOps to GitHub'